version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 864899837235.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t user3/assessment .
      - docker tag user3/assessment:latest 864899837235.dkr.ecr.ap-south-1.amazonaws.com/diptabose484/awstraining:assessment

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 864899837235.dkr.ecr.ap-south-1.amazonaws.com/diptabose484/awstraining:assessment

artifacts:
  files:
    - '**/*'
  name: assessment-artifacts